baseURL = "https://www.robnugen.com/"
languageCode = "en-us"
theme = [ "purehugo" ]
rssLimit = 50
defaultContentLanguageInSubdir = true
[markup.goldmark.renderer]
unsafe= true
[params]
    mainSections = ["events"]
  	author = "Rob Nugen"
    hideSidebarIconText = true
	twitterName = "thunderrabbit"
	githubNameNVM = "thunderrabbit"
	facebook = "barefootrob"
	linkedin = "robnugen"
	description = "keep pushing the limits"
	hideShareOptions = true
[permalinks]
    blog = "/blog/:year/:month/:day/:title/"
    journal = "/journal/:year/:month/:day/:title/"

[languages]
  [languages.en]
    title = "Barefoot Rob"
    weight = 1
    LanguageName = "English"
    description = "Enjoy being on earth"

  [languages.ja]
    title = "裸足のロブ"
    weight = 2
    LanguageName = "日本語"
    description = "Enjoy being on earth"
