#baseURL = "https://www.robnugen.com/"
baseURL = "https://www.robnugen.com/"
languageCode = "en-us"
title = "Barefoot Rob"
theme = ["purehugo-augmentation", "purehugo" ]
[markup.goldmark.renderer]
unsafe= true
[params]
    mainSections = ["blog"]
  	author = "Rob Nugen"
	twitter = "thunderrabbit"
	github = "thunderrabbit"
	facebook = "barefootrob"
	linkedin = "robnugen"
	description = "keep pushing the limits"
	hideShareOptions = true
[permalinks]
    blog = "/blog/:year/:month/:day/:title/"
    journal = "/journal/:year/:month/:day/:title/"
